graph = makeInstance( 'graphical )
lib = symbolToString( 'test )
cell = symbolToString( 'textAcopy )
view = symbolToString( 'layout )
setLib(graph lib)
setCell(graph cell)
setView(graph view)
openWindow(graph)
dbDeleteObject(nth(0 graph->ref~>shapes))
refreshWindow(graph)
saveWindow(graph)
closeWindow(graph)