#!/bin/tcsh
#
#setenv IBMPDK /nfs/foundry/ibm/IBM_PDK
#setenv PROCESS bicmos8hp
setenv PROJDIR ~/projects/mems
#setenv SETUPDIR $IBMPDK/$PROCESS/metInit
setenv SETUPDIR /net/rfctest/vol/vol13/eng/lib/oaLibs/oaTest/oa3/cad/cadence/sim61
setenv EDITOR /usr/bin/emacs
setenv TERM konsole
setenv CDS_CMI_COMPLEVEL 0
setenv QRC_ENABLE_EXTRACTION t

if !(-d ~/projects) then
  mkdir ~/projects
endif

if !(-d $PROJDIR) then
  mkdir $PROJDIR
  cp $SETUPDIR/cds.lib $PROJDIR/cds.lib
  cp $SETUPDIR/display.drf $PROJDIR/display.drf
  cp $SETUPDIR/.cdsinit $PROJDIR/.cdsinit
  cp $SETUPDIR/.cdsenv $PROJDIR/.cdsenv
  cp $SETUPDIR/assura_tech.lib $PROJDIR/assura_tech.lib
endif
cp $SETUPDIR/.cdsplotinit $PROJDIR/.cdsplotinit
cp $SETUPDIR/.simrc $PROJDIR/.simrc


#
# FOR ADS2016.01_u1
#
setenv HPEESOF_DIR /apps/ads/ADS2017
setenv CDS_AUTO_64BIT ALL
setenv CDS_LOAD_ENV CWD
setenv CDS_LIC_FILE 5280@eand-idslnxlic01.and.us.ray.com:5280@emar-lnxlic01.mrl.us.ray.com:5280@epts-lnxlic01.pts.us.ray.com:27338@cadence-license01-gbs.app.ray.com

# FOR CADENCE ARTIST 6.1
setenv INSTALLDIR /apps/cadence/IC616
setenv CDS /apps/cadence/IC616
setenv CDS_HOME /apps/cadence/IC616
setenv ASSURAHOME /apps/assura/ASSURA616_04.14.101
setenv MMSIMHOME /apps/mmsim/MMSIM131
setenv QRC /apps/ext/EXT131
setenv QRC_HOME /apps/ext/EXT131

# Design Kit Specific settings 
setenv CDS_Netlisting_Mode Analog

set path = ($QRC/bin $QRC/tools/bin $HPEESOF_DIR/bin $MMSIMHOME/tools/bin $INSTALLDIR/tools/bin $INSTALLDIR/tools/dfII/bin $ASSURAHOME/tools/bin $ASSURAHOME/tools/assura/bin $ASSURAHOME/tools/dfII/bin $path)

cd $PROJDIR
#umask 007

virtuoso & 
